# Generated by Django 5.2.11 on 2026-02-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
