# Generated by Django 5.2.11 on 2026-02-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_failed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('internship', 'Internship'), ('project', 'Project'), ('hackathon', 'Hackathon')], default='project', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('progress', 'In Progress'), ('success', 'Success'), ('failure', 'Failure')], default='progress', max_length=10),
        ),
    ]
